server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        pageEventConsumer-in-0:
          destination: T1
        pageEventSupplier-out-0:
          destination: T2
          producer:
            poller:
              fixed-delay: 200
        kStreamKStreamFunction-in-0:
          destination: T2
        kStreamKStreamFunction-out-0:
          destination: T3

    function:
      definition: pageEventConsumer; pageEventSupplier; kStreamKStreamFunction
